DROP TABLE IF EXiSTS t_user;

CREATE TABLE t_user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL,
    email TEXT NOT NULL,
    birthday TEXT NOT NULL,
    phone TEXT NOT NULL,
    address TEXT NOT NULL,
    photo TEXT NOT NULL
);